version: "3.4"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  service1:
    build: ./
    tty: true
    entrypoint: npm run dev
    environment:
      - ID=1
      - NAME=service1
    volumes:
      - ./src:/var/www/src
  service2:
    build: ./
    tty: true
    entrypoint: npm run dev
    environment:
      - ID=3
      - NAME=service2
    volumes:
      - ./src:/var/www/src
  service3:
    build: ./
    tty: true
    entrypoint: npm run dev
    environment:
      - ID=2
      - NAME=service3
    volumes:
      - ./src:/var/www/src
